
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

const SUPABASE_URL = "https://whmvgdhodoybcixjaodm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobXZnZGhvZG95YmNpeGphb2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM0MjcsImV4cCI6MjA2MDIyOTQyN30.1X7AaBjetL5ypw2pvfPSpKMb1X0QZU2xAK5yTrD4iXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
